In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("marketing_data.csv")

In [3]:
df

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Response,Complain,Country
0,1826,1970,Graduation,Divorced,84835.0,0,0,2014-06-16,0,189,...,6,1,0,0,0,0,0,1,0,Spain
1,1,1961,Graduation,Single,57091.0,0,0,2014-06-15,0,464,...,7,5,0,0,0,0,1,1,0,Canada
2,10476,1958,Graduation,Married,67267.0,0,1,2014-05-13,0,134,...,5,2,0,0,0,0,0,0,0,USA
3,1386,1967,Graduation,Together,32474.0,1,1,2014-05-11,0,10,...,2,7,0,0,0,0,0,0,0,Australia
4,5371,1989,Graduation,Single,21474.0,1,0,2014-04-08,0,6,...,2,7,1,0,0,0,0,1,0,Spain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10142,1976,PhD,Divorced,66476.0,0,1,2013-03-07,99,372,...,11,4,0,0,0,0,0,0,0,USA
2236,5263,1977,2n Cycle,Married,31056.0,1,0,2013-01-22,99,5,...,3,8,0,0,0,0,0,0,0,Spain
2237,22,1976,Graduation,Divorced,46310.0,1,0,2012-12-03,99,185,...,5,8,0,0,0,0,0,0,0,Spain
2238,528,1978,Graduation,Married,65819.0,0,0,2012-11-29,99,267,...,10,3,0,0,0,0,0,0,0,India
2239,4070,1969,PhD,Married,94871.0,0,2,2012-09-01,99,169,...,4,7,0,1,1,0,0,1,0,Canada

In [4]:

print(df.info())
print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 28 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   object
 3   Marital_Status       2240 non-null   object
 4    Income              2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   object
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  AcceptedCmp3         2240 non-null   int64
 21  AcceptedCmp4         2240 non-null   int64
 22  AcceptedCmp5         2240 non-null   int64
 23  AcceptedCmp1         2240 non-null   int64
 24  AcceptedCmp2         2240 non-null   int64
 25  Response             2240 non-null   int64
 26  Complain             2240 non-null   int64
 27  Country              2240 non-null   object
dtypes: float64(1), int64(23), object(4)
memory usage: 490.1+ KB
None
ID                      0
Year_Birth              0
Education               0
Marital_Status          0
 Income                24
Kidhome                 0
Teenhome                0
Dt_Customer             0
Recency                 0
MntWines                0
MntFruits               0
MntMeatProducts         0
MntFishProducts         0
MntSweetProducts        0
MntGoldProds            0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
AcceptedCmp3            0
AcceptedCmp4            0
AcceptedCmp5            0
AcceptedCmp1            0
AcceptedCmp2            0
Response                0
Complain                0
Country                 0
dtype: int64

In [7]:
df.columns = df.columns.str.strip()   
df.columns = df.columns.str.replace(" ", "_")  
df.columns = df.columns.str.lower()

In [8]:
print(df.columns)

Index(['id', 'year_birth', 'education', 'marital_status', 'income', 'kidhome',
       'teenhome', 'dt_customer', 'recency', 'mntwines', 'mntfruits',
       'mntmeatproducts', 'mntfishproducts', 'mntsweetproducts',
       'mntgoldprods', 'numdealspurchases', 'numwebpurchases',
       'numcatalogpurchases', 'numstorepurchases', 'numwebvisitsmonth',
       'acceptedcmp3', 'acceptedcmp4', 'acceptedcmp5', 'acceptedcmp1',
       'acceptedcmp2', 'response', 'complain', 'country'],
      dtype='object')

In [9]:
df['income'] = df['income'].fillna(df['income'].median())

In [10]:
df = df[df['year_birth'] >= 1920]

In [11]:
Q1 = df['income'].quantile(0.25)
Q3 = df['income'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

df = df[(df['income'] >= lower_bound) & (df['income'] <= upper_bound)]

In [13]:
df['dt_customer'] = pd.to_datetime(df['dt_customer'])

In [14]:
df['age'] = 2026 - df['year_birth']

In [15]:
df['total_spending'] = (
    df['mntwines'] +
    df['mntfruits'] +
    df['mntmeatproducts'] +
    df['mntfishproducts'] +
    df['mntsweetproducts'] +
    df['mntgoldprods']
)

In [16]:
df['total_purchases'] = (
    df['numwebpurchases'] +
    df['numcatalogpurchases'] +
    df['numstorepurchases']
)

In [17]:

df['children'] = df['kidhome'] + df['teenhome']

In [18]:
df['education'] = df['education'].str.strip().str.title()
df['marital_status'] = df['marital_status'].str.strip().str.title()

In [21]:
print(df.columns.tolist())

['id', 'year_birth', 'education', 'marital_status', 'income', 'kidhome', 'teenhome', 'dt_customer', 'recency', 'mntwines', 'mntfruits', 'mntmeatproducts', 'mntfishproducts', 'mntsweetproducts', 'mntgoldprods', 'numdealspurchases', 'numwebpurchases', 'numcatalogpurchases', 'numstorepurchases', 'numwebvisitsmonth', 'acceptedcmp3', 'acceptedcmp4', 'acceptedcmp5', 'acceptedcmp1', 'acceptedcmp2', 'response', 'complain', 'country', 'age', 'total_spending', 'total_purchases', 'children']

In [22]:
print(df.describe())
print(df.head())

                 id   year_birth         income      kidhome     teenhome  \
count   2229.000000  2229.000000    2229.000000  2229.000000  2229.000000
mean    5589.296097  1968.888739   51619.504262     0.444594     0.507402
min        0.000000  1940.000000    1730.000000     0.000000     0.000000
25%     2829.000000  1959.000000   35416.000000     0.000000     0.000000
50%     5455.000000  1970.000000   51381.500000     0.000000     0.000000
75%     8420.000000  1977.000000   68118.000000     1.000000     1.000000
max    11191.000000  1996.000000  113734.000000     2.000000     2.000000
std     3244.840538    11.707430   20601.216248     0.538636     0.544735

                         dt_customer      recency     mntwines    mntfruits  \
count                           2229  2229.000000  2229.000000  2229.000000
mean   2013-07-10 05:20:25.841184512    49.106326   304.991476    26.348587
min              2012-07-30 00:00:00     0.000000     0.000000     0.000000
25%              2013-01-16 00:00:00    24.000000    24.000000     2.000000
50%              2013-07-08 00:00:00    49.000000   176.000000     8.000000
75%              2013-12-30 00:00:00    74.000000   505.000000    33.000000
max              2014-06-29 00:00:00    99.000000  1493.000000   199.000000
std                              NaN    28.946476   336.761943    39.764060

       mntmeatproducts  ...  acceptedcmp4  acceptedcmp5  acceptedcmp1  \
count      2229.000000  ...   2229.000000   2229.000000   2229.000000
mean        165.283984  ...      0.074921      0.072678      0.064603
min           0.000000  ...      0.000000      0.000000      0.000000
25%          16.000000  ...      0.000000      0.000000      0.000000
50%          67.000000  ...      0.000000      0.000000      0.000000
75%         231.000000  ...      0.000000      0.000000      0.000000
max        1725.000000  ...      1.000000      1.000000      1.000000
std         219.336589  ...      0.263324      0.259666      0.245879

       acceptedcmp2     response     complain          age  total_spending  \
count   2229.000000  2229.000000  2229.000000  2229.000000     2229.000000
mean       0.013459     0.149843     0.008973    57.111261      605.541050
min        0.000000     0.000000     0.000000    30.000000        5.000000
25%        0.000000     0.000000     0.000000    49.000000       69.000000
50%        0.000000     0.000000     0.000000    56.000000      397.000000
75%        0.000000     0.000000     0.000000    67.000000     1044.000000
max        1.000000     1.000000     1.000000    86.000000     2525.000000
std        0.115255     0.356998     0.094319    11.707430      601.032228

       total_purchases     children
count      2229.000000  2229.000000
mean         12.549125     0.951996
min           0.000000     0.000000
25%           6.000000     0.000000
50%          12.000000     1.000000
75%          18.000000     1.000000
max          32.000000     3.000000
std           7.181785     0.751976

[8 rows x 29 columns]
      id  year_birth   education marital_status   income  kidhome  teenhome  \
0   1826        1970  Graduation       Divorced  84835.0        0         0
1      1        1961  Graduation         Single  57091.0        0         0
2  10476        1958  Graduation        Married  67267.0        0         1
3   1386        1967  Graduation       Together  32474.0        1         1
4   5371        1989  Graduation         Single  21474.0        1         0

  dt_customer  recency  mntwines  ...  acceptedcmp5  acceptedcmp1  \
0  2014-06-16        0       189  ...             0             0
1  2014-06-15        0       464  ...             0             0
2  2014-05-13        0       134  ...             0             0
3  2014-05-11        0        10  ...             0             0
4  2014-04-08        0         6  ...             0             0

   acceptedcmp2  response  complain    country  age  total_spending  \
0             0         1         0      Spain   56            1190
1             1         1         0     Canada   65             577
2             0         0         0        USA   68             251
3             0         0         0  Australia   59              11
4             0         1         0      Spain   37              91

   total_purchases  children
0               14         0
1               17         0
2               10         1
3                3         2
4                6         1

[5 rows x 32 columns]

In [23]:
df

,id,year_birth,education,marital_status,income,kidhome,teenhome,dt_customer,recency,mntwines,...,acceptedcmp5,acceptedcmp1,acceptedcmp2,response,complain,country,age,total_spending,total_purchases,children
0,1826,1970,Graduation,Divorced,84835.0,0,0,2014-06-16,0,189,...,0,0,0,1,0,Spain,56,1190,14,0
1,1,1961,Graduation,Single,57091.0,0,0,2014-06-15,0,464,...,0,0,1,1,0,Canada,65,577,17,0
2,10476,1958,Graduation,Married,67267.0,0,1,2014-05-13,0,134,...,0,0,0,0,0,USA,68,251,10,1
3,1386,1967,Graduation,Together,32474.0,1,1,2014-05-11,0,10,...,0,0,0,0,0,Australia,59,11,3,2
4,5371,1989,Graduation,Single,21474.0,1,0,2014-04-08,0,6,...,0,0,0,1,0,Spain,37,91,6,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10142,1976,Phd,Divorced,66476.0,0,1,2013-03-07,99,372,...,0,0,0,0,0,USA,50,689,18,1
2236,5263,1977,2N Cycle,Married,31056.0,1,0,2013-01-22,99,5,...,0,0,0,0,0,Spain,49,55,4,1
2237,22,1976,Graduation,Divorced,46310.0,1,0,2012-12-03,99,185,...,0,0,0,0,0,Spain,50,309,12,1
2238,528,1978,Graduation,Married,65819.0,0,0,2012-11-29,99,267,...,0,0,0,0,0,India,48,1383,19,0
2239,4070,1969,Phd,Married,94871.0,0,2,2012-09-01,99,169,...,1,0,0,1,0,Canada,57,1078,17,2

In [24]:
df.to_csv("cleaned_marketing_data.csv", index=False)